# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_NOMADIK) += \
	ste-nomadik-s8815.dtb \
	ste-nomadik-nhk15.dtb
dtb-$(CONFIG_ARCH_U8500) += \
	ste-snowball.dtb \
	ste-hrefprev60-stuib.dtb \
	ste-hrefprev60-tvk.dtb \
	ste-hrefv60plus-stuib.dtb \
	ste-hrefv60plus-tvk.dtb \
	ste-href520-tvk.dtb \
	ste-ux500-samsung-golden.dtb \
	ste-ux500-samsung-janice.dtb \
	ste-ux500-samsung-gavini.dtb \
	ste-ux500-samsung-codina.dtb \
	ste-ux500-samsung-codina-tmo.dtb \
	ste-ux500-samsung-skomer.dtb \
	ste-ux500-samsung-kyle.dtb
