# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)
# Copyright 2025 Gregory CLEMENT <gregory.clement@bootlin.com>

%YAML 1.2
---
$id: http://devicetree.org/schemas/marvell,armada-370-cpu-config.yaml#
$schema: http://devicetree.org/meta-schemas/core.yaml#

title: Marvell Armada 370/XP CPU Config registers

maintainers:
  - Gregory CLEMENT <gregory.clement@bootlin.com>

properties:
  compatible:
    enum:
      - marvell,armada-370-cpu-config
      - marvell,armada-xp-cpu-config

  reg:
    maxItems: 1

required:
  - compatible
  - reg

additionalProperties: false

examples:
  - |
    cpu-config@21000 {
      compatible = "marvell,armada-xp-cpu-config";
      reg = <0x21000 0x8>;
    };
