#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only

import os
import glob
import re
import argparse

func_type_map = {
	'u8': 'uint8',
	's8': 'int8',
	'u16': 'uint16',
	's16': 'int16',
	'u32': 'uint32',
	's32': 'int32',
}

def parse_of_property_funcs(props, data):
	""" Find all property strings in *_property_read_*() functions """
	for m in re.finditer(r'(_property_(for_each|read|match)_[a-zA-Z0-9_]+)\([a-zA-Z0-9_&>\-*]+,\s"([^"]+)"', data):
		func = m[1]
		propname = m[3]
		c_type = re.search(r'([us](8|16|32|64)|bool|string)', func)[1]
		prop_type = func_type_map.get(c_type, c_type)
		if '_index' in func or '_array' in func or '_for_each' in func:
			prop_type += '-array'

		props.setdefault(propname, [])
		if prop_type not in props[propname]:
			props[propname] += [prop_type]


def parse_of_find_get_property_funcs(props, data):
	""" Find all property strings in of_get_property/of_find_property """
	for m in re.finditer(r'of_(find|get)_property\([a-zA-Z0-9_&>\-*]+,\s"([^"]+)"', data):
		props.setdefault(m[2], [])


def parse_property_present_funcs(props, data):
	""" Find all property strings in of_get_property/of_find_property """
	for m in re.finditer(r'_property_present\([a-zA-Z0-9_&>\-*]+,\s"([^"]+)"', data):
		if m[1] not in props:
			props[m[1]] = ['bool']


def parse_properties(props, file):
	with open(file, 'r', encoding='utf-8') as f:
		data = f.read().replace('\n', '')

	parse_of_property_funcs(props, data)
	parse_of_find_get_property_funcs(props, data)
	parse_property_present_funcs(props, data)

def print_properties(props):
	if not props:
		return
	if show_type:
		for p,t in props.items():
			t.sort()
			prop_str = ' '.join(t)
			print(f'{p}: {prop_str}')
	else:
		print(*props.keys(), sep='\n')

show_type = False

if __name__ == "__main__":
	ap = argparse.ArgumentParser()
	ap.add_argument("cfile", type=str, nargs='*', help="C source files or directories to parse")
	ap.add_argument('-t', '--show-type', help="Print type(s) information with properties", action="store_true")
	args = ap.parse_args()

	show_type = args.show_type

	props = {}
	for f in args.cfile:
		if os.path.isdir(f):
			for filename in glob.iglob(f + "/**/*.c", recursive=True):
				parse_properties(props, filename)
		else:
			parse_properties(props, f)

	print_properties(props)
