# SPDX-License-Identifier: GPL-2.0
# Keep at91 dtb files sorted alphabetically for each SoC
dtb-$(CONFIG_MACH_KIRKWOOD) += \
	kirkwood-netgear_readynas_nv+_v2.dtb \

o
o
dtb-$(CONFIG_SOC_DRA7XX) += \
	am57xx-evm-reva3.dtb \


subdir-y += actions
subdir-y += airoha
subdir-y += allwinner
subdir-y += alphascale
subdir-y += alpine
subdir-y += arm
subdir-y += aspeed
subdir-y += axis
subdir-y += berlin
subdir-y += brcm
subdir-y += calxeda
subdir-y += cirrus
subdir-y += cnxt
subdir-y += fsl
subdir-y += gemini
subdir-y += hisilicon
subdir-y += hpe
subdir-y += imx
subdir-y += intel
subdir-y += lpc
subdir-y += lsi
subdir-y += marvell
subdir-y += mediatek
subdir-y += meson
subdir-y += microchip
subdir-y += moxa
subdir-y += mstar
subdir-y += mxs
subdir-y += nspire
subdir-y += nuvoton
subdir-y += nvidia
subdir-y += pxa
subdir-y += qcom
subdir-y += rda
subdir-y += realtek
subdir-y += renesas
subdir-y += rockchip
subdir-y += samsung
subdir-y += socfpga
subdir-y += socionext
subdir-y += spear
subdir-y += st-ericsson
subdir-y += sti
subdir-y += stm32
subdir-y += ti
subdir-y += vt8500
subdir-y += xen
subdir-y += xilinx
